apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ibtg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ibtg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ibtg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ibtg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ibtg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qczo-tenant/rhtap-demo-app/hacbs-test-project-ibtg@sha256:c88f7e204f70e9420acd1b33c7c64dcc9373e4dd429757d0f2968157b219b1c3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
